# Generated by Django 3.0.5 on 2020-04-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Brussel', 'Brussel'), ('Leuven', 'Leuven'), ('Gent', 'Gent'), ('Antwerpen', 'Antwerpen')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('DIFF', 'DIFF')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Placed', 'Placed'), ('Reserved', 'Reserved')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Algoritmes', 'Algoritmes'), ('Analyses', 'Analyses'), ('Informatica', 'Informatica')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.CharField(choices=[('Erasmushogeschool | EHB', (('Campus Kaai', 'Campus Kaai'), ('Campus Bloemberg', 'Campus Bloemberg'))), ('Vrije Universiteit Brussel | VUB', (('Campus Jette', 'Campus Jette'), ('Campus Schaarbeek', 'Campus Schaarbeek'))), ('Katholieke universiteit leuven | KUL', (('KUL Gent', 'KUL Gent'), ('Campus Antwerpen', 'Campus Antwerpen')))], max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Category')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Condition')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Location')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Major')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.State')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Subject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title')},
                'index_together': {('user', 'title')},
            },
        ),
    ]
