# Generated by Django 3.0.6 on 2020-05-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to='post_image')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('school', models.CharField(choices=[('Erasmushogeschool | EHB', (('Campus Kaai', 'Campus Kaai'), ('Campus Bloemberg', 'Campus Bloemberg'))), ('Vrije Universiteit Brussel | VUB', (('Campus Jette', 'Campus Jette'), ('Campus Schaarbeek', 'Campus Schaarbeek'))), ('Katholieke universiteit leuven | KUL', (('KUL Gent', 'KUL Gent'), ('Campus Antwerpen', 'Campus Antwerpen')))], max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Category')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Condition')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Location')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Major')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Subject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title')},
                'index_together': {('user', 'title')},
            },
        ),
    ]
