# Generated by Django 3.0.5 on 2020-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Pending', 'Pending'), ('Placed', 'Placed')], max_length=200, null=True),
        ),
    ]
