# Generated by Django 3.0.6 on 2020-05-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
    ]
