# Generated by Django 3.0.5 on 2020-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200501_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
    ]
