# Generated by Django 3.0.6 on 2020-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
