# Generated by Django 3.0.6 on 2020-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_product_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.CharField(choices=[('Odisee', 'Odisee'), ('LUCA School of Arts', 'LUCA School of Arts'), ('Erasmushogeschool Brussel', 'Erasmushogeschool Brussel'), ('Artesis Plantijn Hogeschool', 'Artesis Plantijn Hogeschool'), ('Karel de Grote-Hogeschool', 'Karel de Grote-Hogeschool'), ('Thomas More', 'Thomas More'), ('UC Leuven', 'UC Leuven'), ('Hogeschool PXL', 'Hogeschool PXL'), ('UC Limburg', 'UC Limburg'), ('Hogeschool West-Vlaanderen', 'Hogeschool West-Vlaanderen'), ('Katholieke Hogeschool Vives', 'Katholieke Hogeschool Vives'), ('Hogeschool Gent Geraard', 'Hogeschool Gent\tGeraard'), ('Arteveldehogeschool', 'Arteveldehogeschool'), ('Vrije Universiteit Brussel', 'Vrije Universiteit Brussel'), ('Universiteit Antwerpen', 'Universiteit Antwerpen'), ('Katholieke Universiteit Leuven', 'Katholieke Universiteit Leuven'), ('Universiteit Hasselt', 'Universiteit Hasselt'), ('Universiteit Gent', 'Universiteit Gent')], max_length=50, null=True),
        ),
    ]
