# Generated by Django 3.0.6 on 2020-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200518_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.CharField(choices=[('Erasmushogeschool | EHB', (('Campus Kaai', 'Campus Kaai'), ('Campus Bloemberg', 'Campus Bloemberg'))), ('Vrije Universiteit Brussel | VUB', (('Campus Jette', 'Campus Jette'), ('Campus Schaarbeek', 'Campus Schaarbeek'))), ('Katholieke universiteit leuven | KUL', (('KUL Gent', 'KUL Gent'), ('Campus Antwerpen', 'Campus Antwerpen')))], max_length=50, null=True),
        ),
    ]
