# Generated by Django 3.0.5 on 2020-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200505_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Algoritmes', 'Algoritmes'), ('Analyses', 'Analyses'), ('Informatica', 'Informatica')], max_length=200, null=True),
        ),
    ]
