# Generated by Django 3.0.6 on 2020-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200518_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(choices=[('Handelsingenieur', 'Handelsingenieur'), ('Industriële wetenschappen Energie', 'Industriële wetenschappen Energie'), ('Biowetenschappen', 'Biowetenschappen'), ('Architectuur', 'Architectuur'), ('International Business', 'International Business'), ('Fysica', 'Fysica'), ('Wiskunde', 'Wiskunde'), ('Wijsbegeerte', 'Wijsbegeerte'), ('Kunstwetenschappen', 'Kunstwetenschappen'), ('Taal- en letterkunde', 'Taal- en letterkunde'), ('Geologie', 'Geologie'), ('Informatica', 'Informatica'), ('Rechten', 'Rechten'), ('Geschiedenis', 'Geschiedenis'), ('Beeldende kunsten', 'Beeldende kunsten'), ('Visual Arts', 'Visual Arts'), ('Drama', 'Drama'), ('Muziek', 'Muziek'), ('Chemie', 'Chemie'), ('Biomedische laboratoriumtechnologie', 'Biomedische laboratoriumtechnologie'), ('Bedrijfsmanagement', 'Bedrijfsmanagement'), ('Journalistiek', 'Journalistiek'), ('Office management', 'Office management'), ('Transport en logistiek', 'Transport en logistiek')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Wiskunde', 'Wiskunde'), ('Algoritmes', 'Algoritmes'), ('Analyses', 'Analyses'), ('Informatica', 'Informatica'), ('Fysica', 'Fysica'), ('Wijsbegeerte', 'Wijsbegeerte'), ('Geologie', 'Geologie'), ('Psychologie', 'Psychologie'), ('Godsdienst', 'Godsdienst'), ('Frans', 'Frans'), ('Engels', 'Engels'), ('Duits', 'Duits'), ('Biologie', 'Biologie'), ('Toerisme', 'Toerisme'), ('Economie', 'Economie'), ('Toneel', 'Toneel'), ('Audiovisuele vorming', 'Audiovisuele vorming')], max_length=200, null=True),
        ),
    ]
