# Generated by Django 3.0.6 on 2020-05-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20200518_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='state',
        ),
    ]
