# Generated by Django 3.0.5 on 2020-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20200506_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.CharField(choices=[('Erasmushogeschool | EHB', (('CampusKaai', 'CampusKaai'), ('Campus Bloemberg', 'Campus Bloemberg'))), ('Vrije Universiteit Brussel | VUB', (('Campus Jette', 'Campus Jette'), ('Campus Schaarbeek', 'Campus Schaarbeek'))), ('Katholieke universiteit leuven | KUL', (('KUL Gent', 'KUL Gent'), ('Campus Antwerpen', 'Campus Antwerpen')))], max_length=50, null=True),
        ),
    ]
