# Generated by Django 3.0.5 on 2020-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20200506_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, null=True)),
                ('answer', models.TextField(max_length=800, null=True)),
            ],
        ),
    ]
