# Generated by Django 3.0.6 on 2020-05-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20200520_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.School'),
        ),
    ]
