# Generated by Django 3.0.6 on 2020-05-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_product_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Major'),
        ),
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.School'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.Subject'),
        ),
    ]
