# Generated by Django 3.0.6 on 2020-05-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20200513_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
