# Generated by Django 3.0.6 on 2020-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20200513_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='post_image'),
        ),
    ]
