# Generated by Django 3.0.6 on 2020-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
