# Generated by Django 3.0.6 on 2020-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('Brussel', 'Brussel'), ('Leuven', 'Leuven'), ('Gent', 'Gent'), ('Antwerpen', 'Antwerpen'), ('Namen', 'Namen')], max_length=200, null=True),
        ),
    ]
